background {
    path = /home/rana/Pictures/wallpapers/6_lock.jpg
    blur_passes = 2
    blur_size = 6
    brightness = 0.6
    zindex = -1
}

input-field {
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgba(137, 180, 250, 0.8)
    inner_color = rgba(30, 30, 46, 0.9)
    font_color = rgb(205, 214, 244)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}

label {
    text = $TIME
    color = rgba(205, 214, 244, 1.0)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

label {
    text = Hi, $USER
    color = rgba(205, 214, 244, 0.8)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 20
    halign = center
    valign = center
}
