[General]

Background="Backgrounds/6_lock.jpg"
DimBackgroundImage="0.2"
ScaleImageCropped="true"

ScreenWidth="1920"
ScreenHeight="1080"

FullBlur="false"
PartialBlur="true"
BlurRadius="80"

HaveFormBackground="true"
FormPosition="center"
BackgroundImageHAlignment="center"
BackgroundImageVAlignment="center"

MainColor="white"
AccentColor="#89b4fa"
BackgroundColor="rgba(30,30,46,0.7)"
OverrideLoginButtonTextColor="#1e1e2e"

InterfaceShadowSize="6"
InterfaceShadowOpacity="0.6"
RoundCorners="20"
ScreenPadding="0"

Font="JetBrains Mono"
FontSize=""

ForceRightToLeft="false"
ForceLastUser="true"
ForcePasswordFocus="true"
ForceHideCompletePassword="false"
ForceHideVirtualKeyboardButton="true"
ForceHideSystemButtons="false"
AllowEmptyPassword="false"
AllowBadUsernames="false"

HourFormat="HH:mm"
DateFormat="dddd, d MMMM"

HeaderText="Welcome Back"
